bump `_version.py` from 0.5.1 to 0.6.0.dev0
databricks/megablocks pull request #148
Opened 2024-08-30 20:55 UTC by eitanturok

# What does this PR do?

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/databricks/megablocks/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/databricks/megablocks/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/databricks/megablocks/blob/dev/CONTRIBUTING.md#prerequisites))

2024-08-30 21:02 UTC, snarayan21 reviewed
0.6.0 not 0.6.1 haha

2024-08-30 21:02 UTC, snarayan21 commented on megablocks/_version.py
> +__version__ = '0.6.1.dev0'
```suggestion
__version__ = '0.6.0.dev0'
```
should be this

2024-08-30 21:12 UTC, snarayan21 approved these changes
lgtm!

2024-08-30 23:18 UTC, dakinggg approved these changes

2024-08-31 00:01 UTC, snarayan21 requested changes
blocking merge until after i patch release

2024-08-31 15:22 UTC, merged